export const LUCIDE_ICONS = [
    { label: "Check", name: "Check" },
    { label: "Chevron Right", name: "ChevronRight" },
    { label: "Chevron Left", name: "ChevronLeft" },
    { label: "Chevron Up", name: "ChevronUp" },
    { label: "Chevron Down", name: "ChevronDown" },
    { label: "Arrow Right", name: "ArrowRight" },
    { label: "Arrow Left", name: "ArrowLeft" },
    { label: "External Link", name: "ExternalLink" },
    { label: "Mail", name: "Mail" },
    { label: "Phone", name: "Phone" },
    { label: "Map Pin", name: "MapPin" },
    { label: "Globe", name: "Globe" },
    { label: "Search", name: "Search" },
    { label: "Settings", name: "Settings" },
    { label: "User", name: "User" },
    { label: "Users", name: "Users" },
    { label: "Heart", name: "Heart" },
    { label: "Star", name: "Star" },
    { label: "Sparkles", name: "Sparkles" },
    { label: "Zap", name: "Zap" },
    { label: "Code", name: "Code" },
    { label: "Cpu", name: "Cpu" },
    { label: "Database", name: "Database" },
    { label: "Cloud", name: "Cloud" },
    { label: "Lock", name: "Lock" },
    { label: "Unlock", name: "Unlock" },
    { label: "Shield", name: "Shield" },
    { label: "Bell", name: "Bell" },
    { label: "Calendar", name: "Calendar" },
    { label: "Clock", name: "Clock" },
    { label: "Watch", name: "Watch" },
    { label: "Bookmark", name: "Bookmark" },
    { label: "Tag", name: "Tag" },
    { label: "Package", name: "Package" },
    { label: "Truck", name: "Truck" },
    { label: "Shopping Cart", name: "ShoppingCart" },
    { label: "Credit Card", name: "CreditCard" },
    { label: "Dollar Sign", name: "DollarSign" },
    { label: "Wallet", name: "Wallet" },
    { label: "Briefcase", name: "Briefcase" },
    { label: "Building", name: "Building" },
    { label: "Home", name: "Home" },
    { label: "Layout", name: "Layout" },
    { label: "Layers", name: "Layers" },
    { label: "Image", name: "Image" },
    { label: "Video", name: "Video" },
    { label: "Music", name: "Music" },
    { label: "Mic", name: "Mic" },
    { label: "Headphones", name: "Headphones" },
    { label: "Camera", name: "Camera" },
    { label: "Monitor", name: "Monitor" },
    { label: "Smartphone", name: "Smartphone" },
    { label: "Laptop", name: "Laptop" },
    { label: "Tablet", name: "Tablet" },
    { label: "Cpu", name: "Cpu" },
    { label: "Server", name: "Server" },
    { label: "Wifi", name: "Wifi" },
    { label: "Activity", name: "Activity" },
    { label: "Bar Chart", name: "BarChart" },
    { label: "Pie Chart", name: "PieChart" },
    { label: "Line Chart", name: "LineChart" },
    { label: "Trending Up", name: "TrendingUp" },
    { label: "Trending Down", name: "TrendingDown" },
    { label: "Smile", name: "Smile" },
    { label: "Frown", name: "Frown" },
    { label: "Meh", name: "Meh" },
    { label: "Info", name: "Info" },
    { label: "Help Circle", name: "HelpCircle" },
    { label: "Alert Circle", name: "AlertCircle" },
    { label: "Alert Triangle", name: "AlertTriangle" },
    { label: "Check Circle", name: "CheckCircle" },
    { label: "X Circle", name: "XCircle" },
    { label: "Thumbs Up", name: "ThumbsUp" },
    { label: "Thumbs Down", name: "ThumbsDown" },
    { label: "Message Square", name: "MessageSquare" },
    { label: "Message Circle", name: "MessageCircle" },
    { label: "Send", name: "Send" },
    { label: "Share", name: "Share" },
    { label: "Share 2", name: "Share2" },
    { label: "Link", name: "Link" },
    { label: "Copy", name: "Copy" },
    { label: "Trash", name: "Trash" },
    { label: "Plus", name: "Plus" },
    { label: "Minus", name: "Minus" },
    { label: "X", name: "X" },
    { label: "Menu", name: "Menu" },
    { label: "More Horizontal", name: "MoreHorizontal" },
    { label: "More Vertical", name: "MoreVertical" },
    { label: "Eye", name: "Eye" },
    { label: "Eye Off", name: "EyeOff" },
    { label: "Download", name: "Download" },
    { label: "Upload", name: "Upload" },
    { label: "Lightbulb", name: "Lightbulb" },
    { label: "Rocket", name: "Rocket" },
    { label: "Flame", name: "Flame" },
    { label: "Ghost", name: "Ghost" },
    { label: "Moon", name: "Moon" },
    { label: "Sun", name: "Sun" },
    { label: "Sunrise", name: "Sunrise" },
    { label: "Sunset", name: "Sunset" },
    { label: "Wind", name: "Wind" },
    { label: "Cloud Rain", name: "CloudRain" },
    { label: "Cloud Lightning", name: "CloudLightning" },
    { label: "Cloud Snow", name: "CloudSnow" },
    { label: "Umbrella", name: "Umbrella" },
    { label: "Filter", name: "Filter" },
    { label: "Maximize", name: "Maximize" },
    { label: "Minimize", name: "Minimize" },
    { label: "Refresh", name: "RefreshCw" },
    { label: "Shuffle", name: "Shuffle" },
    { label: "Volume 2", name: "Volume2" },
    { label: "Volume X", name: "VolumeX" },
    { label: "Map", name: "Map" },
    { label: "File", name: "File" },
    { label: "File Text", name: "FileText" },
    { label: "Folder", name: "Folder" },
    { label: "Edit", name: "Edit" },
    { label: "Pen Tool", name: "PenTool" },
    { label: "Dribbble", name: "Dribbble" },
    { label: "Twitter", name: "Twitter" },
    { label: "Github", name: "Github" },
    { label: "Linkedin", name: "Linkedin" },
    { label: "Facebook", name: "Facebook" },
    { label: "Instagram", name: "Instagram" },
    { label: "Youtube", name: "Youtube" },
    { label: "Slack", name: "Slack" },
];
